name: simple Cache

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-cache-

      - name: Install dependencies
        run: npm install
        working-directory: ./  # adjust if package.json is in a subfolder

      - name: Build project
        run: npm run build
        working-directory: ./  # adjust if needed

